server:
  port: 9096
spring:
  application:
    name: kapcb
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  elasticsearch:
    rest:
      uris: 192.168.80.135:9200
      read-timeout: 30s
      connection-timeout: 5s

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # true : 当查询数据为空时字段返回为 null, false : 不加这个查询数据为空时字段将被隐藏
    call-setters-on-nulls: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.kapcb.ccc.model.po
  global-config:
    db-config:
      logic-delete-value: true
      logic-not-delete-value: false
      logic-delete-field: deleteFlag

