server:
  port: 9096
spring:
  application:
    name: kapcb
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  elasticsearch:
    rest:
      uris:
      read-timeout: 30s
      connection-timeout: 5s