server:
  port: 9096
spring:
  application:
    name: kapcb
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#  elasticsearch:
#    rest:
#      uris: 192.168.80.135:9200
#      read-timeout: 30s
#      connection-timeout: 5s

#  security:
#    user:
#      name: kapcb
#      password: 123456

  datasource:
    hikari:
      idle-timeout: 30000 # 空闲等待时间
      minimum-idle: 5 # 最小连接数
      maximum-pool-size: 10 # 连接池中最大连接数
      connection-timeout: 20000 # 连接超时时间
      auto-commit: true
      max-lifetime: 1800000
      connection-test-query: select 1
      pool-name: KapcbHikariCP
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_grp?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8
    username: root
    password: 123456
#  redis:
#    host: 192.168.80.129
#    database: 0
#    port: 6379
#    password: ccc
#    lettuce:
#      pool:
#        min-idle: 8
#        max-idle: 500
#        max-active: 2000
#        max-wait: 10000
#      shutdown-timeout: 5000

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # true : 当查询数据为空时字段返回为 null, false : 不加这个查询数据为空时字段将被隐藏
    call-setters-on-nulls: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.kapcb.ccc.model.po
  global-config:
    db-config:
      logic-delete-value: true
      logic-not-delete-value: false
      logic-delete-field: deleteFlag
logging:
  config: classpath:logback.xml
  level:
    root: info
kapcb:
  end:
    point:
      enable: true
      exception-message: true
      application-name: true
      class-name: true
      method-name: true
      request-cost-time: true
      request-time: true
      request-uri: true
      request-url: true
      return-value: true
